language: python
cache: pip
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: pypy
    - python: pypy3

# msoffcrypto-tool causes issues on PyPy
#install:
#  - pip install msoffcrypto-tool

script:
  - python setup.py test
